/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUserRouteImport } from './routes/admin.user'
import { Route as AdminOrderRouteImport } from './routes/admin.order'
import { Route as AdminGoogleUserRouteImport } from './routes/admin.google-user'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCheckdomainRouteImport } from './routes/admin.checkdomain'
import { Route as AdminAdministratorRouteImport } from './routes/admin.administrator'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserRoute = AdminUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrderRoute = AdminOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoogleUserRoute = AdminGoogleUserRouteImport.update({
  id: '/google-user',
  path: '/google-user',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckdomainRoute = AdminCheckdomainRouteImport.update({
  id: '/checkdomain',
  path: '/checkdomain',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministratorRoute = AdminAdministratorRouteImport.update({
  id: '/administrator',
  path: '/administrator',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/administrator': typeof AdminAdministratorRoute
  '/admin/checkdomain': typeof AdminCheckdomainRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/google-user': typeof AdminGoogleUserRoute
  '/admin/order': typeof AdminOrderRoute
  '/admin/user': typeof AdminUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/administrator': typeof AdminAdministratorRoute
  '/admin/checkdomain': typeof AdminCheckdomainRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/google-user': typeof AdminGoogleUserRoute
  '/admin/order': typeof AdminOrderRoute
  '/admin/user': typeof AdminUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/administrator': typeof AdminAdministratorRoute
  '/admin/checkdomain': typeof AdminCheckdomainRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/google-user': typeof AdminGoogleUserRoute
  '/admin/order': typeof AdminOrderRoute
  '/admin/user': typeof AdminUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/administrator'
    | '/admin/checkdomain'
    | '/admin/dashboard'
    | '/admin/google-user'
    | '/admin/order'
    | '/admin/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/administrator'
    | '/admin/checkdomain'
    | '/admin/dashboard'
    | '/admin/google-user'
    | '/admin/order'
    | '/admin/user'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/administrator'
    | '/admin/checkdomain'
    | '/admin/dashboard'
    | '/admin/google-user'
    | '/admin/order'
    | '/admin/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user': {
      id: '/admin/user'
      path: '/user'
      fullPath: '/admin/user'
      preLoaderRoute: typeof AdminUserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/order': {
      id: '/admin/order'
      path: '/order'
      fullPath: '/admin/order'
      preLoaderRoute: typeof AdminOrderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/google-user': {
      id: '/admin/google-user'
      path: '/google-user'
      fullPath: '/admin/google-user'
      preLoaderRoute: typeof AdminGoogleUserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkdomain': {
      id: '/admin/checkdomain'
      path: '/checkdomain'
      fullPath: '/admin/checkdomain'
      preLoaderRoute: typeof AdminCheckdomainRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administrator': {
      id: '/admin/administrator'
      path: '/administrator'
      fullPath: '/admin/administrator'
      preLoaderRoute: typeof AdminAdministratorRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdministratorRoute: typeof AdminAdministratorRoute
  AdminCheckdomainRoute: typeof AdminCheckdomainRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGoogleUserRoute: typeof AdminGoogleUserRoute
  AdminOrderRoute: typeof AdminOrderRoute
  AdminUserRoute: typeof AdminUserRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministratorRoute: AdminAdministratorRoute,
  AdminCheckdomainRoute: AdminCheckdomainRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGoogleUserRoute: AdminGoogleUserRoute,
  AdminOrderRoute: AdminOrderRoute,
  AdminUserRoute: AdminUserRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
