/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MailRouteImport } from './routes/mail'
import { Route as LoginRouteImport } from './routes/login'
import { Route as E2eeRouteImport } from './routes/e2ee'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MailTrashRouteImport } from './routes/mail.trash'
import { Route as MailSpamRouteImport } from './routes/mail.spam'
import { Route as MailSentRouteImport } from './routes/mail.sent'
import { Route as MailNewRouteImport } from './routes/mail.new'
import { Route as MailInboxRouteImport } from './routes/mail.inbox'
import { Route as MailImportantRouteImport } from './routes/mail.important'
import { Route as MailGroupsGroupIdRouteImport } from './routes/mail.groups.$groupId'

const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eeRoute = E2eeRouteImport.update({
  id: '/e2ee',
  path: '/e2ee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailTrashRoute = MailTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => MailRoute,
} as any)
const MailSpamRoute = MailSpamRouteImport.update({
  id: '/spam',
  path: '/spam',
  getParentRoute: () => MailRoute,
} as any)
const MailSentRoute = MailSentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => MailRoute,
} as any)
const MailNewRoute = MailNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MailRoute,
} as any)
const MailInboxRoute = MailInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => MailRoute,
} as any)
const MailImportantRoute = MailImportantRouteImport.update({
  id: '/important',
  path: '/important',
  getParentRoute: () => MailRoute,
} as any)
const MailGroupsGroupIdRoute = MailGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => MailRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e2ee': typeof E2eeRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRouteWithChildren
  '/mail/important': typeof MailImportantRoute
  '/mail/inbox': typeof MailInboxRoute
  '/mail/new': typeof MailNewRoute
  '/mail/sent': typeof MailSentRoute
  '/mail/spam': typeof MailSpamRoute
  '/mail/trash': typeof MailTrashRoute
  '/mail/groups/$groupId': typeof MailGroupsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e2ee': typeof E2eeRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRouteWithChildren
  '/mail/important': typeof MailImportantRoute
  '/mail/inbox': typeof MailInboxRoute
  '/mail/new': typeof MailNewRoute
  '/mail/sent': typeof MailSentRoute
  '/mail/spam': typeof MailSpamRoute
  '/mail/trash': typeof MailTrashRoute
  '/mail/groups/$groupId': typeof MailGroupsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e2ee': typeof E2eeRoute
  '/login': typeof LoginRoute
  '/mail': typeof MailRouteWithChildren
  '/mail/important': typeof MailImportantRoute
  '/mail/inbox': typeof MailInboxRoute
  '/mail/new': typeof MailNewRoute
  '/mail/sent': typeof MailSentRoute
  '/mail/spam': typeof MailSpamRoute
  '/mail/trash': typeof MailTrashRoute
  '/mail/groups/$groupId': typeof MailGroupsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/e2ee'
    | '/login'
    | '/mail'
    | '/mail/important'
    | '/mail/inbox'
    | '/mail/new'
    | '/mail/sent'
    | '/mail/spam'
    | '/mail/trash'
    | '/mail/groups/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e2ee'
    | '/login'
    | '/mail'
    | '/mail/important'
    | '/mail/inbox'
    | '/mail/new'
    | '/mail/sent'
    | '/mail/spam'
    | '/mail/trash'
    | '/mail/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/e2ee'
    | '/login'
    | '/mail'
    | '/mail/important'
    | '/mail/inbox'
    | '/mail/new'
    | '/mail/sent'
    | '/mail/spam'
    | '/mail/trash'
    | '/mail/groups/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  E2eeRoute: typeof E2eeRoute
  LoginRoute: typeof LoginRoute
  MailRoute: typeof MailRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2ee': {
      id: '/e2ee'
      path: '/e2ee'
      fullPath: '/e2ee'
      preLoaderRoute: typeof E2eeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/trash': {
      id: '/mail/trash'
      path: '/trash'
      fullPath: '/mail/trash'
      preLoaderRoute: typeof MailTrashRouteImport
      parentRoute: typeof MailRoute
    }
    '/mail/spam': {
      id: '/mail/spam'
      path: '/spam'
      fullPath: '/mail/spam'
      preLoaderRoute: typeof MailSpamRouteImport
      parentRoute: typeof MailRoute
    }
    '/mail/sent': {
      id: '/mail/sent'
      path: '/sent'
      fullPath: '/mail/sent'
      preLoaderRoute: typeof MailSentRouteImport
      parentRoute: typeof MailRoute
    }
    '/mail/new': {
      id: '/mail/new'
      path: '/new'
      fullPath: '/mail/new'
      preLoaderRoute: typeof MailNewRouteImport
      parentRoute: typeof MailRoute
    }
    '/mail/inbox': {
      id: '/mail/inbox'
      path: '/inbox'
      fullPath: '/mail/inbox'
      preLoaderRoute: typeof MailInboxRouteImport
      parentRoute: typeof MailRoute
    }
    '/mail/important': {
      id: '/mail/important'
      path: '/important'
      fullPath: '/mail/important'
      preLoaderRoute: typeof MailImportantRouteImport
      parentRoute: typeof MailRoute
    }
    '/mail/groups/$groupId': {
      id: '/mail/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/mail/groups/$groupId'
      preLoaderRoute: typeof MailGroupsGroupIdRouteImport
      parentRoute: typeof MailRoute
    }
  }
}

interface MailRouteChildren {
  MailImportantRoute: typeof MailImportantRoute
  MailInboxRoute: typeof MailInboxRoute
  MailNewRoute: typeof MailNewRoute
  MailSentRoute: typeof MailSentRoute
  MailSpamRoute: typeof MailSpamRoute
  MailTrashRoute: typeof MailTrashRoute
  MailGroupsGroupIdRoute: typeof MailGroupsGroupIdRoute
}

const MailRouteChildren: MailRouteChildren = {
  MailImportantRoute: MailImportantRoute,
  MailInboxRoute: MailInboxRoute,
  MailNewRoute: MailNewRoute,
  MailSentRoute: MailSentRoute,
  MailSpamRoute: MailSpamRoute,
  MailTrashRoute: MailTrashRoute,
  MailGroupsGroupIdRoute: MailGroupsGroupIdRoute,
}

const MailRouteWithChildren = MailRoute._addFileChildren(MailRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  E2eeRoute: E2eeRoute,
  LoginRoute: LoginRoute,
  MailRoute: MailRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
